server.port=8080

spring.profiles.active=h2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

app.upload-dir=./uploads
