# Default embedded file DB. This keeps the existing data file format/location.
spring.datasource.url=jdbc:h2:file:./data/messenger-db;MODE=LEGACY;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
