# Alternative embedded file DB. No external DB server is required.
# Data files are created under ./data/messenger-hsqldb.*
spring.datasource.url=jdbc:hsqldb:file:./data/messenger-hsqldb;shutdown=true
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.HSQLDialect
